Oe/start screen/add start screen
archimatchproject/mobile pull request #13
Opened 2024-07-03 11:27 UTC by guardian-001

## What does this do?

add start screen and commit initial husky errors fix

## Why did you do this?

to ensure that updates on all branches

2024-07-03 14:04 UTC, guardian-001 commented
The number of files is high because I resolved all the Husky errors

2024-07-03 14:50 UTC, MohamedMegdich1 requested changes

2024-07-03 14:50 UTC, MohamedMegdich1 commented on src/assets/icons/archimatch/animation.tsx
Please change the file name.

2024-07-03 14:50 UTC, MohamedMegdich1 commented on src/assets/icons/archimatch/complete-logo-client.tsx
> +        height="117px"
Why are you fixing the height and the width?

2024-07-03 14:50 UTC, MohamedMegdich1 commented on src/assets/icons/archimatch/complete-logo.tsx
> +    fill="none"
the same

2024-07-03 14:50 UTC, MohamedMegdich1 commented on src/assets/icons/archimatch/house-icon.tsx
> +    height={22}
the same

2024-07-03 14:50 UTC, MohamedMegdich1 commented on src/assets/icons/archimatch/house-image.tsx
> +    height={44}
the same

2024-07-03 14:50 UTC, MohamedMegdich1 commented on package.json
> +  "lint-staged": {
Why are you adding lint-staged in package.json?

2024-07-03 14:50 UTC, MohamedMegdich1 commented on src/modules/shared/main-button.tsx
> +      className={`${height} ${width} ${radius} flex  ${shadow} ${alternativeStyle}`}
Why not use a style merge?

2024-07-03 14:50 UTC, MohamedMegdich1 commented on src/shared/components/focus-aware-status-bar.tsx
> +  const isDark = false;
Remove the isDark if we don't use it anymore

2024-07-03 14:50 UTC, MohamedMegdich1 commented on src/shared/components/image copy.tsx
Please make sure to pay attention to the naming of the file.

2024-07-03 14:50 UTC, MohamedMegdich1 commented on src/shared/components/image copy.tsx
> +  placeholder = 'L6PZfSi_.AyE_3t7t7R**0o#DgR4',
What is this placeholder?

2024-07-03 14:50 UTC, MohamedMegdich1 commented on src/shared/components/image-container.tsx
> +  // const containerStyle: ViewStyle = { width, height };style={containerStyle}
Feel free to remove the text below if you don't need it.

2024-07-03 14:50 UTC, MohamedMegdich1 commented on src/shared/components/select.tsx
> +    const isDark = false;
the same

2024-07-03 15:34 UTC, guardian-001 commented on src/assets/icons/archimatch/animation.tsx
deleted. file not used

2024-07-03 15:37 UTC, guardian-001 commented on src/assets/icons/archimatch/complete-logo-client.tsx
> +        height="117px"
![image](https://github.com/archimatchproject/mobile/assets/171500984/7be7a654-ccc3-4368-8a2e-0388fe302e53)



fixed

2024-07-03 15:40 UTC, guardian-001 commented on src/assets/icons/archimatch/complete-logo.tsx
> +    fill="none"
![image](https://github.com/archimatchproject/mobile/assets/171500984/c69ae415-209a-4e4e-a971-d043d3868e2c)
 fixed

2024-07-03 15:43 UTC, guardian-001 commented on src/assets/icons/archimatch/house-icon.tsx
> +    height={22}
I didn't implement them, I found them in the template

2024-07-03 15:43 UTC, guardian-001 commented on src/assets/icons/archimatch/complete-logo.tsx
> +    fill="none"
I didn't implement them, I found them in the template

2024-07-03 15:43 UTC, guardian-001 commented on src/assets/icons/archimatch/house-image.tsx
> +    height={44}
I didn't implement them, I found them in the template

2024-07-03 15:45 UTC, guardian-001 commented on src/assets/icons/archimatch/house-image.tsx
> +    height={44}
![image](https://github.com/archimatchproject/mobile/assets/171500984/69ac9668-e460-4d84-88a7-04fe792ae00d)
 fixed

2024-07-03 15:46 UTC, guardian-001 commented on package.json
> +  "lint-staged": {
"I wanted to ignore the assets folder from type check because I found a problem in resolving some types in React Native SVG, but later I found the solution

2024-07-03 15:47 UTC, guardian-001 commented on package.json
> +  "lint-staged": {
![image](https://github.com/archimatchproject/mobile/assets/171500984/09857824-63a6-4b88-a384-ef4f4c920e71)
deleted

2024-07-03 15:51 UTC, guardian-001 commented on src/modules/shared/main-button.tsx
> +      className={`${height} ${width} ${radius} flex  ${shadow} ${alternativeStyle}`}
![image](https://github.com/archimatchproject/mobile/assets/171500984/d30d159d-69f0-4e23-8b1b-236f75615bca)
 fixed

2024-07-03 15:52 UTC, guardian-001 commented on src/shared/components/focus-aware-status-bar.tsx
> +  const isDark = false;
I left it to make it easier for us if we decide to implement the dark theme later

2024-07-03 15:53 UTC, guardian-001 commented on src/shared/components/image copy.tsx
Sorry, it was by copy paste mistake

2024-07-03 15:54 UTC, guardian-001 commented on src/shared/components/image copy.tsx
> +  placeholder = 'L6PZfSi_.AyE_3t7t7R**0o#DgR4',
Haha, I don't know, it's an existing component from the template. I will fix it

2024-07-03 15:55 UTC, guardian-001 commented on src/shared/components/image copy.tsx
> +  placeholder = 'L6PZfSi_.AyE_3t7t7R**0o#DgR4',
![image](https://github.com/archimatchproject/mobile/assets/171500984/394a05cc-abda-484d-a6c7-bb4e1e6eed27)
fixed

2024-07-03 15:55 UTC, guardian-001 commented on src/shared/components/image-container.tsx
> +  // const containerStyle: ViewStyle = { width, height };style={containerStyle}
![image](https://github.com/archimatchproject/mobile/assets/171500984/35ded32b-070b-48d1-94fa-fb454109df7a)
cleaned

2024-07-03 15:56 UTC, guardian-001 commented on src/shared/components/select.tsx
> +    const isDark = false;
I left it to make it easier for us if we decide to implement the dark theme later

2024-07-04 07:13 UTC, MohamedMegdich1 approved these changes

2024-07-04 07:13 UTC, merged