feat(resetPass): add reset password interface
archimatchproject/mobile pull request #15
Opened 2024-07-04 12:07 UTC by AzizSandid

## What does this do?

create  reset password interface 

## Why did you do this?

To allow users to reset their passwords easily and securely.

## How did you test this?
![Screenshot_20240704-122939_archimatch](https://github.com/archimatchproject/mobile/assets/171419700/8d2f33bd-c840-4cd0-99fe-e11bbd95e079)
![Screenshot_20240704-122738_archimatch](https://github.com/archimatchproject/mobile/assets/171419700/f49a12bd-d843-4e79-b9be-635b65e9da8a)
![Screenshot_20240704-122724_archimatch](https://github.com/archimatchproject/mobile/assets/171419700/c819a56f-5a75-4fee-a60a-e11c996f38b2)
![Screenshot_20240704-122713_archimatch](https://github.com/archimatchproject/mobile/assets/171419700/c464c4ce-1c43-47a1-b476-a9101ba2013f)

2024-07-04 15:23 UTC, MohamedMegdich1 requested changes

2024-07-04 15:23 UTC, MohamedMegdich1 commented on src/assets/icons/archimatch/design-inter.tsx
> +  <Svg width={115} height={104} fill="none" {...props}>
Please remember not to set fixed width and height.

2024-07-04 15:23 UTC, MohamedMegdich1 commented on src/assets/icons/archimatch/house-model.tsx
> +  <Svg width={100} height={100} fill="none" {...props}>
the same

2024-07-04 15:23 UTC, MohamedMegdich1 commented on src/assets/icons/tick-icon.tsx
> +  <Svg width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}>
the same

2024-07-04 15:23 UTC, MohamedMegdich1 commented on src/assets/images/CodeCerificationBlue.png
Watch out for the file naming.

2024-07-04 15:23 UTC, MohamedMegdich1 commented on src/assets/images/CodeCerificationRed.png
the same kebab case

2024-07-04 15:23 UTC, MohamedMegdich1 commented on src/modules/reset-password/otp-input.tsx
> +  rules?: any;
why any type ?

2024-07-04 15:23 UTC, MohamedMegdich1 commented on src/modules/reset-password/reset-form-email.tsx
> +      required_error: 'Email is required',
Please translate the message and make sure to use the validation that has been shared.

2024-07-04 15:23 UTC, MohamedMegdich1 commented on src/modules/reset-password/reset-form-password.tsx
> +          isValid={/[^a-zA-Z0-9]/.test(password)}
Do you think this is the best method to do it? I think you can define a list and use it instead.

2024-07-04 15:23 UTC, MohamedMegdich1 commented on src/modules/reset-password/reset-stepper.tsx
> +                ? require('@/assets/images/CodeCerificationBlue.png')
Why not export the SVG image and change the color based on the context?

2024-07-04 15:23 UTC, MohamedMegdich1 commented on src/modules/reset-password/verification-code.tsx
> +const schema = z.object({
the same for the schema

2024-07-04 16:17 UTC, AzizSandid commented on src/assets/icons/archimatch/design-inter.tsx
> +  <Svg width={115} height={104} fill="none" {...props}>
fixed

2024-07-04 16:17 UTC, AzizSandid commented on src/assets/icons/archimatch/house-model.tsx
> +  <Svg width={100} height={100} fill="none" {...props}>
fixed

2024-07-04 16:18 UTC, AzizSandid commented on src/assets/icons/tick-icon.tsx
> +  <Svg width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}>
fixed

2024-07-04 16:18 UTC, AzizSandid commented on src/assets/images/CodeCerificationBlue.png
fixed

2024-07-04 16:18 UTC, AzizSandid commented on src/assets/images/CodeCerificationRed.png
fixed

2024-07-04 16:18 UTC, AzizSandid commented on src/modules/reset-password/otp-input.tsx
> +  rules?: any;
fixed

2024-07-04 16:19 UTC, AzizSandid commented on src/modules/reset-password/reset-form-email.tsx
> +      required_error: 'Email is required',
fixed

2024-07-04 16:23 UTC, AzizSandid commented on src/modules/reset-password/verification-code.tsx
> +const schema = z.object({
fixed

2024-07-04 16:24 UTC, AzizSandid commented on src/modules/reset-password/reset-stepper.tsx
> +                ? require('@/assets/images/CodeCerificationBlue.png')
![image](https://github.com/archimatchproject/mobile/assets/171419700/290e4f12-37f5-4805-958d-f7db634f01da)
it's image nt svg i can't change the color

2024-07-04 20:30 UTC, guardian-001 commented on src/modules/reset-password/reset-stepper.tsx
> +                ? require('@/assets/images/CodeCerificationBlue.png')
Basically, it's a PNG image, but when exported from Figma as an SVG, it just encapsulates the PNG image in an SVG file

2024-07-05 07:52 UTC, MohamedMegdich1 requested changes

2024-07-05 07:52 UTC, MohamedMegdich1 commented on src/assets/icons/tick-icon.tsx
> +const TickIcon: React.FC<TickIconProps> = ({ color = '#000', ...props }) => (
Change the color to a non-static color.

2024-07-05 08:18 UTC, AzizSandid commented on src/assets/icons/tick-icon.tsx
> +const TickIcon: React.FC<TickIconProps> = ({ color = '#000', ...props }) => (
fixed

2024-07-05 08:25 UTC, MohamedMegdich1 approved these changes

2024-07-05 08:25 UTC, merged