feat(react-hook,card): integrate reat hook form in checkbox radio switch and create toggle card
archimatchproject/mobile pull request #17
Opened 2024-07-04 13:37 UTC by AzizSandid

## What does this do?

Integrates React Hook Form with checkboxes, radio buttons, switches, and creates a toggle card. 
## Why did you do this?

To improve form handling and validation in the application by leveraging React Hook Form's capabilities for better state management and performance.

2024-07-04 14:19 UTC, MohamedMegdich1 requested changes

2024-07-04 14:19 UTC, MohamedMegdich1 commented on src/shared/components/checkbox-input.tsx
> +  rules?: any;
Why are you using any type?

2024-07-04 14:19 UTC, MohamedMegdich1 commented on src/shared/components/checkbox.tsx
> +import { Pressable, type PressableProps, View } from 'react-native';
why not import from shared/component

2024-07-04 14:19 UTC, MohamedMegdich1 commented on src/shared/components/radio-input.tsx
> +  rules?: any; // Adjust the type according to your validation rules
the same

2024-07-04 14:19 UTC, MohamedMegdich1 commented on src/shared/components/switch-input.tsx
> +  rules?: any; // Adjust the type according to your validation rules
the same

2024-07-04 14:19 UTC, MohamedMegdich1 commented on src/shared/components/toggle-card.tsx
> +  rules?: any; // Adjust the type according to your validation rules
the same

2024-07-04 16:01 UTC, AzizSandid commented on src/shared/components/checkbox-input.tsx
> +  rules?: any;
fixed

2024-07-04 16:01 UTC, AzizSandid commented on src/shared/components/checkbox.tsx
> +import { Pressable, type PressableProps, View } from 'react-native';
fixed

2024-07-04 16:01 UTC, AzizSandid commented on src/shared/components/radio-input.tsx
> +  rules?: any; // Adjust the type according to your validation rules
fixed

2024-07-04 16:01 UTC, AzizSandid commented on src/shared/components/toggle-card.tsx
> +  rules?: any; // Adjust the type according to your validation rules
fixed

2024-07-05 07:59 UTC, MohamedMegdich1 requested changes

2024-07-05 08:29 UTC, AzizSandid commented on src/shared/components/select.tsx
> +import { Platform, TouchableOpacity, View } from '@/shared/components';
fixed

2024-07-05 08:30 UTC, AzizSandid commented on src/shared/components/switch-input.tsx
> +import type {
fixed

2024-07-05 08:38 UTC, AzizSandid commented on src/shared/components/toggle-card.tsx
> +  Control,
fixed

2024-07-05 08:46 UTC, AzizSandid commented on src/shared/components/checkbox-input.tsx
> +import type {
fixed

2024-07-05 08:53 UTC, MohamedMegdich1 approved these changes

2024-07-05 08:53 UTC, merged