fix(fixes-&-simple-feats): shared-comps-&-resetpass-header-&-some-gen…
archimatchproject/mobile pull request #20
Opened 2024-07-06 20:37 UTC by guardian-001

## What does this do?

- optimized imports in shared components
- add custom header for reset password stepper (header-title.tsx component)
- make reset password stepper usable for client and architect
- add routing to reset password from login (for architect and client)
- fixed back button functioning

## Why did you do this?

These changes were made to improve the usability and functionality of the reset password process. By optimizing imports, we ensure that our shared components are more efficient. The custom header provides a clear and distinct stepper for the reset password process, enhancing the user experience for both clients and architects. Adding routing and fixing the back button functionality ensures a smoother and more intuitive navigation, reducing user frustration and improving overall workflow.

## Who/what does this impact?

These changes impact the reset password functionality used by both clients and architects. The updates to the shared components and routing might also have downstream effects on other parts of the application that rely on these components

2024-07-08 08:35 UTC, MohamedMegdich1 requested changes

2024-07-08 08:35 UTC, MohamedMegdich1 commented on src/app/(architect)/(public)/_layout.tsx
> +        options={{
why repeat this code, extract it and reused

2024-07-08 08:35 UTC, MohamedMegdich1 commented on src/modules/shared/back-button.tsx
> +    if (route) {
what is the logic of this function?

2024-07-08 08:50 UTC, guardian-001 commented on src/app/(architect)/(public)/_layout.tsx
> +        options={{
![image](https://github.com/archimatchproject/mobile/assets/171500984/e1ee2db8-c1a0-4e63-8cb3-198053805fc7)
![image](https://github.com/archimatchproject/mobile/assets/171500984/cb905dc0-fe96-4d32-be86-cd05a6852cf4)
![image](https://github.com/archimatchproject/mobile/assets/171500984/58978a7a-d94b-49b7-ba68-ba4bf54589de)
fixed

2024-07-08 08:51 UTC, guardian-001 commented on src/modules/shared/back-button.tsx
> +    if (route) {
![image](https://github.com/archimatchproject/mobile/assets/171500984/b009e4b1-c515-440d-9594-337e8979abb8)

2024-07-09 04:24 UTC, guardian-001 commented on src/app/(architect)/(public)/_layout.tsx
> +        options={{
![IMG_0888](https://github.com/archimatchproject/mobile/assets/171500984/7c368515-f441-46a5-8e6c-14f992ac4725)
![IMG_0889](https://github.com/archimatchproject/mobile/assets/171500984/80eafd72-c5ad-4ef0-a2b4-70a336516c97)
I added the options to shared component

2024-07-09 08:08 UTC, MohamedMegdich1 requested changes

2024-07-09 08:08 UTC, MohamedMegdich1 commented on src/shared/components/screen-options.tsx
> +  headerTransparent: true,
Why not pass props instead of copying it?

2024-07-09 10:57 UTC, guardian-001 commented on src/shared/components/screen-options.tsx
> +  headerTransparent: true,
fixed

2024-07-09 10:59 UTC, guardian-001 commented on src/shared/components/screen-options.tsx
> +  headerTransparent: true,
![image](https://github.com/archimatchproject/mobile/assets/171500984/f9cecd6a-057f-4b02-acbc-402957e2c7bd)
![image](https://github.com/archimatchproject/mobile/assets/171500984/14892bfc-44ec-4572-9f8d-fa25b0186891)
![image](https://github.com/archimatchproject/mobile/assets/171500984/621200c3-1482-4104-98b0-bf63b693d3b9)

2024-07-09 11:12 UTC, MohamedMegdich1 commented on src/shared/components/screen-options.tsx
> +  headerTransparent: true,
if you don't pass anything in the ScreenOptions, it will default to 'init'. I think you should test it first.

2024-07-09 13:26 UTC, merged