Aj/86bz12uff/login forn
archimatchproject/mobile pull request #23
Opened 2024-07-09 11:02 UTC by Ahmedjaziri3

## What does this do?

This pull request enhances the supplier login interface in the Archimatch app:

- **Added Assets:** Introduced a new PNG file ("supplier login.png") for visual representation.
- **Updated Components:** Modified `LoginForm` component in `login-form-supplier.tsx` to incorporate controlled inputs for email validation using `react-hook-form`.
- **Improved User Experience:** Implemented responsive design using `KeyboardAvoidingView` to ensure optimal display on both iOS and Android platforms.

## Why did you do this?

These changes aim to streamline the supplier login process, improving usability and visual appeal across different devices accessing Archimatch.

## Who/what does this impact?

- **Developers:** Team members working on related components should review the changes, particularly those handling form submissions and UI updates.
- **Users:** Suppliers using the Archimatch app will experience a more intuitive and responsive login interface.

## How did you test this?

- Verified functionality of `react-hook-form` integration with controlled inputs for email validation.
- Tested responsiveness and layout consistency using `KeyboardAvoidingView` on iOS and Android devices.
- Confirmed correct rendering of the new PNG file ("supplier login.png") across various screen resolutions.

These steps ensure the reliability and usability of the updated supplier login feature in Archimatch.
## Some photos showcasing the changes :

![325e1c16-b851-479c-858b-b53f620d3736](https://github.com/archimatchproject/mobile/assets/171420161/a1333e0a-d53c-45e6-afe2-dcc334472920)

![4befeac9-f1cd-44bc-b344-8d0dbdac060d](https://github.com/archimatchproject/mobile/assets/171420161/560d832f-083e-48fd-95bf-48894a9aa0cb)

2024-07-09 11:20 UTC, MohamedMegdich1 requested changes

2024-07-09 11:20 UTC, MohamedMegdich1 commented on src/modules/login/login-form-supplier.tsx
> +          {'Bienvenue sur Archimatch'}
add the translation for this line

2024-07-09 11:20 UTC, MohamedMegdich1 commented on src/modules/login/login-form-supplier.tsx
> +          {'Kit Partenariat PRO'}
the same

2024-07-09 11:20 UTC, MohamedMegdich1 commented on src/app/(supplier)/(public)/login.tsx
> +import type { LoginFormProps } from '@/modules/login/login-form-supplier';
The type should be in the folder types

2024-07-09 11:20 UTC, MohamedMegdich1 commented on src/app/(supplier)/(public)/_layout.tsx
> +        options={{
It would be best if you changed the option from the branch of Oussama

2024-07-12 11:49 UTC, MohamedMegdich1 requested changes

2024-07-12 11:49 UTC, MohamedMegdich1 commented on src/modules/login/login-form-supplier.tsx
> +              source={require('@/assets/Supplier login.png')}
why the image name with space

2024-07-12 11:49 UTC, MohamedMegdich1 commented on src/translations/fr/loginSupplier.json
> +  "Supporting Text": "Texte de support",
Remember to follow the convention for naming translations.

2024-07-12 11:49 UTC, MohamedMegdich1 commented on src/translations/en/loginSupplier.json
> +  "Se connecter": "Login",
Remember to follow the convention for naming translations.

2024-07-12 11:49 UTC, MohamedMegdich1 commented on src/translations/ar/loginSupplier.json
> +  "Se connecter": "تسجيل الدخول",
Remember to follow the convention for naming translations.

2024-07-12 11:49 UTC, MohamedMegdich1 commented on src/modules/login/login-form.test.tsx
> +        email: 'example@gmail.com', // Corrected expected value to match input
Extract it into a constant for better readability

2024-07-12 11:53 UTC, Ahmedjaziri3 commented on src/modules/login/login-form-supplier.tsx
> +              source={require('@/assets/Supplier login.png')}
Waiting for the .gif version

2024-08-02 10:31 UTC, closed without merging