As/86bz13hv7/gestion profil
archimatchproject/mobile pull request #27
Opened 2024-07-11 13:06 UTC by AzizSandid

## What does this do?

-add interface reset password and basic information and notifications
-I don't use the translation in the basic information interface because Jaziri has created her translation but has not yet pushed it.

## Why did you do this?

To improve user experience by adding features for resetting passwords, updating basic information, and managing notifications. The translation for the basic information interface is pending because Jaziri has not pushed it yet.

## Who/what does this impact?

nothing

2024-07-11 15:29 UTC, MohamedMegdich1 requested changes

2024-07-11 15:29 UTC, MohamedMegdich1 commented on src/modules/profile/basic-info-form.tsx
> +          name="lastName"
plz add the translation

2024-07-11 15:29 UTC, MohamedMegdich1 commented on src/modules/profile/client-profile.tsx
> +              router.push(`/(client)/(private)/(profile)/basic-information/`);
Consider extracting it into a separate function to avoid duplicating the same code.

2024-07-11 15:29 UTC, MohamedMegdich1 commented on src/modules/profile/notification-form.tsx
> +          accessibilityLabel="Nouveau pour vous"
add the translation

2024-07-11 15:29 UTC, MohamedMegdich1 commented on src/validations/shared/shared-schema.tsx
> +  new: z.boolean(),
add a schema for boolean field

2024-07-11 16:01 UTC, AzizSandid commented on src/modules/profile/basic-info-form.tsx
> +          name="lastName"
![image](https://github.com/archimatchproject/mobile/assets/171419700/5e136346-fb08-4acb-9140-6d2e961f26ed)

2024-07-11 16:01 UTC, AzizSandid commented on src/modules/profile/notification-form.tsx
> +          accessibilityLabel="Nouveau pour vous"
![image](https://github.com/archimatchproject/mobile/assets/171419700/92e87ce1-58c7-436f-a137-438a41a0c532)

2024-07-11 19:35 UTC, AzizSandid commented on src/modules/profile/client-profile.tsx
> +              router.push(`/(client)/(private)/(profile)/basic-information/`);
fixed

2024-07-11 19:55 UTC, AzizSandid commented on src/validations/shared/shared-schema.tsx
> +  new: z.boolean(),
fixed

2024-07-12 09:07 UTC, MohamedMegdich1 requested changes

2024-07-12 09:07 UTC, MohamedMegdich1 commented on src/modules/profile/notification-form.tsx
> +            accessibilityLabel="Nouveau pour vous"
Why not convert accessibilityLabel?

2024-07-12 09:07 UTC, MohamedMegdich1 commented on src/modules/profile/client-profile.tsx
> +              navigateTo(`/(client)/(private)/(profile)/notification/`)
/(client)/(private)/(profile) If these parameters are the same for all, why not extract them and change the specific route only?

2024-07-12 09:34 UTC, AzizSandid commented on src/modules/profile/client-profile.tsx
> +              navigateTo(`/(client)/(private)/(profile)/notification/`)
fixed 
![image](https://github.com/user-attachments/assets/c070b11b-eaf6-4ba9-9f9d-2a1a56931b28)
I changed it like that because in the next PR
I will use `/client/private/project`.  /(client)/(private)/(project)

2024-07-12 09:34 UTC, AzizSandid commented on src/modules/profile/notification-form.tsx
> +            accessibilityLabel="Nouveau pour vous"
fixed

2024-07-12 09:48 UTC, MohamedMegdich1 approved these changes

2024-07-12 09:48 UTC, merged