As/projet
archimatchproject/mobile pull request #32
Opened 2024-07-15 14:52 UTC by AzizSandid

## What does this do?

This adds a stepper for publishing a project and includes its translation.

The stepper is not complete; only Step 1 is finished.

2024-07-15 16:47 UTC, MohamedMegdich1 requested changes

2024-07-15 16:47 UTC, MohamedMegdich1 commented on src/validations/shared/shared-schema.tsx
> +  matricule: fieldValidation, //matriculeValidation
in english plz

2024-07-15 16:47 UTC, MohamedMegdich1 commented on src/modules/client/pubication-projet/steps/choose-speciality.tsx
> +        <ToggleCard
extarct this into a list

2024-07-15 16:47 UTC, MohamedMegdich1 commented on src/modules/client/pubication-projet/publication-projet-stepper.tsx
> +  const handleNextStep = () => {
extarct into a hook

2024-07-16 08:21 UTC, AzizSandid commented on src/validations/shared/shared-schema.tsx
> +  matricule: fieldValidation, //matriculeValidation
fixed

2024-07-16 08:21 UTC, AzizSandid commented on src/modules/client/pubication-projet/steps/choose-speciality.tsx
> +        <ToggleCard
fixed

2024-07-16 09:15 UTC, AzizSandid commented on src/modules/client/pubication-projet/publication-projet-stepper.tsx
> +  const handleNextStep = () => {
fixed

2024-07-16 12:21 UTC, MohamedMegdich1 requested changes

2024-07-16 12:21 UTC, MohamedMegdich1 commented on src/modules/client/pubication-projet/steps/save-project.tsx
> +import StepperButton from '@/modules/shared/stepper-button';
why not from @/modules/shared

2024-07-17 07:06 UTC, MohamedMegdich1 requested changes

2024-07-17 07:06 UTC, MohamedMegdich1 commented on src/modules/client/pubication-projet/steps/choose-speciality.tsx
> +import useCustomForm from '@/shared/hooks/use-custom-form';
why importing from the file directly import useCustomForm from '@/shared/hooks/use-custom-form';

2024-07-17 07:06 UTC, MohamedMegdich1 commented on src/modules/client/pubication-projet/publication-projet-stepper.tsx
> +        {step !== 11 && (
i want to extract this const 11

2024-07-17 07:06 UTC, MohamedMegdich1 commented on src/app/(client)/(private)/(projet)/_layout.tsx
> +        options={{ headerShown: false }}
why not using screen option

2024-07-17 07:06 UTC, MohamedMegdich1 commented on src/app/(client)/(private)/(projet)/publication-projet.tsx
> +    <LinearGradient
I don't want to use the component directly from the library; extract it into a reusable component instead.

2024-07-17 07:06 UTC, MohamedMegdich1 commented on src/app/(client)/(private)/_layout.tsx
>        <Stack.Screen name="(tab)" options={{ headerShown: false }} />
the same for screen option

2024-07-17 07:23 UTC, MohamedMegdich1 requested changes

2024-07-17 07:23 UTC, MohamedMegdich1 commented on src/modules/client/pubication-projet/steps/choose-speciality.tsx
> +            isSelected={selectedSpeciality === cardData.selectedSpeciality}
extract to toggle List and isSelected={selectedSpeciality === cardData.selectedSpeciality} move it instead the ToogleCard

2024-07-17 08:13 UTC, AzizSandid commented on src/modules/client/pubication-projet/steps/choose-speciality.tsx
> +import useCustomForm from '@/shared/hooks/use-custom-form';
fixed

2024-07-17 08:28 UTC, AzizSandid commented on src/modules/client/pubication-projet/publication-projet-stepper.tsx
> +        {step !== 11 && (
fixed

2024-07-17 08:50 UTC, AzizSandid commented on src/app/(client)/(private)/(projet)/_layout.tsx
> +        options={{ headerShown: false }}
fixed :'(

2024-07-17 09:06 UTC, AzizSandid commented on src/modules/client/pubication-projet/steps/choose-speciality.tsx
> +            isSelected={selectedSpeciality === cardData.selectedSpeciality}
I can't move it in ToggleCard because in the other steps I will use it like that
![image](https://github.com/user-attachments/assets/7da47197-4602-419e-8f10-2fffb82691d4)

2024-07-17 10:04 UTC, AzizSandid commented on src/app/(client)/(private)/_layout.tsx
>        <Stack.Screen name="(tab)" options={{ headerShown: false }} />
fixed

2024-07-17 10:05 UTC, AzizSandid commented on src/app/(client)/(private)/(projet)/publication-projet.tsx
> +    <LinearGradient
fixed

2024-07-17 11:01 UTC, MohamedMegdich1 approved these changes

2024-07-17 11:01 UTC, merged