feat: api consommation & project stepper & shared comp & folder struc…
archimatchproject/mobile pull request #36
Opened 2024-07-22 16:20 UTC by guardian-001

## What does this do?

- Created project realization stepper
- Implemented categories and styles consumption form realization stepper
- Integrated login API consumption
- Integrated reset password API consumption
- Developed shared components
- Updated translations
- Organized folders and files structure
- Applied various fixes in client and supplier codes
- Structured and organized schemas and validations

## Why did you do this?

These changes were made to enhance the overall user experience by implementing a clear and structured stepper process for project realization, consumption of categories and styles, and user authentication. The updates aim to improve code organization, maintainability, and adherence to best practices, ensuring a more seamless and efficient development workflow. Fixes in client and supplier codes address existing issues and improve functionality. Additionally, the shared components and updated translations enhance reusability and localization support.

## Who/what does this impact?

These changes impact the development team, particularly those working on project realization, API integrations, and form handling. The structured schemas and validations will be crucial for developers working on data management and form validation. The fixes in client and supplier codes may affect downstream processes and dependent components. Developers involved in localization should be aware of the translation updates. Key stakeholders and relevant developers should be notified of these changes to stay informed and aligned.

2024-07-23 08:34 UTC, MohamedMegdich1 requested changes

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/api/architect/project/types.ts
> +export type Category = {
category type should be shared

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/api/architect/project/use-styles.tsx
> +      const response = await client.get(`/api/users/architectural-styles`, {
use axios interceptor

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/app/(app)/_layout.tsx
> +      <Stack.Screen name="index" options={{ headerShown: false }} />
use screenOption

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/app/(architect)/(private)/_layout.tsx
> +      <Stack.Screen name="realize-project" options={{ headerShown: false }} />
use screenOption

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/app/_layout.tsx
>          <Stack.Screen name="(app)" options={{ headerShown: false }} />
use screenOption

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/modules/architect/realization/adopted-style.tsx
> +  const renderItem = ({ item }: any) => (
don't render item in side another component extract it instead and don't use the naming item

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/modules/architect/realization/project-category.tsx
> +  const renderItem = ({ item }: any) => (
the same

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/modules/architect/realization/project-category.tsx
> +            <View>
create a reusable component for pending

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/modules/architect/realization/project-category.tsx
> +            <View>
and the same for error

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/validations/shared/shared-validations.tsx
> +    z.number().int({
images are array of numbers ??

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/validations/shared/shared-validations.tsx
> +    message: 'validations.required',
Is this field required or optional?

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/translations/fr/resetpass.json
>    "password-digit": "un chiffre",
why using kebab case

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/translations/en/resetpass.json
>    "password-digit": "one digit",
why using kebab case

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/shared/components/toggle-card.tsx
> +            source={{ uri: `${Env.API_URL}${image}` }}
Create a hook that performs this task.

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/shared/components/calendar.tsx
> +import { DemoFormSchema } from '@/modules/architect/schemas';
Why use a custom schema for shared components?

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/shared/components/calendar.tsx
> +import type { SignupFormDataType } from '@/modules/architect/types';
the same

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/modules/shared/stepper-percentage-bar.tsx
> +  const percentage = maxStep && (step / maxStep) * 100;
Add a stepCount function that calculates the number of steps based on the passed component.

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/modules/shared/stepper-percentage-bar.tsx
> +      {step !== 5 && (
pass it as a props not fix

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/modules/reset-password/verification-code.tsx
> +import { useFormStepper } from '@/shared/providers/use-form-stepper-provider';
@/shared/providers

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/modules/reset-password/reset-stepper.tsx
> +function ResetStepperInner() {
Why are we removing the initialStep props?

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/modules/reset-password/reset-stepper.tsx
>    const stepsContent: {
Please make sure to discuss with Aziz the method of handling props.

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/modules/reset-password/reset-form-password.tsx
>    const passwordRequirements: { isValid: boolean; message: TxKeyPath }[] = [
i want this to be extract as shared to be used by all of you

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/modules/reset-password/reset-form-password.tsx
> +  const allRequirementsValid = passwordRequirements.every(
Why are you adding this function?

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/modules/reset-password/reset-form-email.tsx
> +      onError: () => {},
What should we do if an error occurs?

2024-07-23 08:34 UTC, MohamedMegdich1 commented on src/modules/login/login-form.tsx
> +      onError: () => {},
What should we do if an error occurs?

2024-07-23 08:36 UTC, MohamedMegdich1 requested changes

2024-07-23 08:36 UTC, MohamedMegdich1 commented on src/app/(client)/(private)/(profile)/reset-password-client.tsx
> -      <ResetStepper initialStep={1} />
why removing intialStep ??

2024-07-23 08:36 UTC, MohamedMegdich1 commented on src/app/(client)/(private)/(projet)/publication-projet.tsx
> -import PublicationProjetStepper from '@/modules/client/pubication-projet/publication-projet-stepper';
why calling architect stepper in client stepper

2024-07-23 08:39 UTC, guardian-001 commented on src/api/architect/project/types.ts
> +export type Category = {
done

2024-07-23 08:43 UTC, guardian-001 commented on src/api/architect/project/use-styles.tsx
> +      const response = await client.get(`/api/users/architectural-styles`, {
![image](https://github.com/user-attachments/assets/014a3da2-9d49-4971-8f87-476c7ec0c9ba)
![image](https://github.com/user-attachments/assets/f1b0786a-8d08-4544-b447-0e9fa3ceab2d)
Done

2024-07-23 08:53 UTC, guardian-001 commented on src/app/(app)/_layout.tsx
> +      <Stack.Screen name="index" options={{ headerShown: false }} />
done

2024-07-23 08:53 UTC, guardian-001 commented on src/app/(architect)/(private)/_layout.tsx
> +      <Stack.Screen name="realize-project" options={{ headerShown: false }} />
done

2024-07-23 08:53 UTC, guardian-001 commented on src/app/_layout.tsx
>          <Stack.Screen name="(app)" options={{ headerShown: false }} />
done

2024-07-23 09:10 UTC, guardian-001 commented on src/modules/architect/realization/project-category.tsx
> +  const renderItem = ({ item }: any) => (
![image](https://github.com/user-attachments/assets/d6f8311b-68d2-4a82-8315-e4429fefe4d5)
![image](https://github.com/user-attachments/assets/719312f8-9472-4957-9e43-4ea12c131460)
fixed

2024-07-23 09:22 UTC, guardian-001 commented on src/modules/architect/realization/project-category.tsx
> +            <View>
![image](https://github.com/user-attachments/assets/ded47f63-26ca-48bf-bc58-dd97d759326e)
done

2024-07-23 09:47 UTC, guardian-001 commented on src/validations/shared/shared-validations.tsx
> +    z.number().int({
fixed

2024-07-23 09:47 UTC, guardian-001 commented on src/validations/shared/shared-validations.tsx
> +    message: 'validations.required',
i changed it to required

2024-07-23 09:54 UTC, guardian-001 commented on src/translations/fr/resetpass.json
>    "password-digit": "un chiffre",
fixed

2024-07-23 09:54 UTC, guardian-001 commented on src/translations/en/resetpass.json
>    "password-digit": "one digit",
fixed

2024-07-23 09:59 UTC, guardian-001 commented on src/shared/components/toggle-card.tsx
> +            source={{ uri: `${Env.API_URL}${image}` }}
fixed

2024-07-23 10:03 UTC, guardian-001 commented on src/shared/components/calendar.tsx
> +import { DemoFormSchema } from '@/modules/architect/schemas';
![image](https://github.com/user-attachments/assets/ba900d52-b0f1-4c84-850e-cbf46a47e4e9)
fixed

2024-07-23 10:48 UTC, guardian-001 commented on src/shared/components/calendar.tsx
> +import type { SignupFormDataType } from '@/modules/architect/types';
fixed

2024-07-23 10:48 UTC, guardian-001 commented on src/shared/components/calendar.tsx
> +import type { SignupFormDataType } from '@/modules/architect/types';
![image](https://github.com/user-attachments/assets/0ba6b77d-71c2-49a9-b5c8-bfb598fe8387)

2024-07-23 10:51 UTC, guardian-001 commented on src/modules/shared/stepper-percentage-bar.tsx
> +      {step !== 5 && (
![image](https://github.com/user-attachments/assets/4209e94c-6a84-451a-9cdc-2364a399fb60)

fixed

2024-07-23 10:54 UTC, guardian-001 commented on src/modules/reset-password/verification-code.tsx
> +import { useFormStepper } from '@/shared/providers/use-form-stepper-provider';
fixed

2024-07-23 10:55 UTC, guardian-001 commented on src/modules/reset-password/reset-stepper.tsx
> +function ResetStepperInner() {
unusable prop

2024-07-23 10:58 UTC, guardian-001 commented on src/modules/reset-password/reset-stepper.tsx
>    const stepsContent: {
i told aziz, and it's better to use the use form stepper functions and states tan creating states inside the components

2024-07-23 11:03 UTC, guardian-001 commented on src/modules/reset-password/reset-form-password.tsx
>    const passwordRequirements: { isValid: boolean; message: TxKeyPath }[] = [
I can’t because setFormData and onHandleNext are two functions coming from useFormStepper. I could move all this logic inside the onHandleNext function, but doing so would make onHandleNext less flexible and less usable in different situations. It’s better to leave it as it is."

Does that work for you?

2024-07-23 11:06 UTC, guardian-001 commented on src/modules/reset-password/reset-form-password.tsx
> +  const allRequirementsValid = passwordRequirements.every(
It wasn’t me who created this component; it was Aziz. I just made changes to set up the stepper hook, ensure that validations work with the submit function, and added API consumption

2024-07-23 11:07 UTC, guardian-001 commented on src/modules/reset-password/reset-form-email.tsx
> +      onError: () => {},
throw iit hhh 
![image](https://github.com/user-attachments/assets/1099fbbf-a003-4004-98f6-96f744872f86)
fixed

2024-07-23 11:07 UTC, guardian-001 commented on src/modules/login/login-form.tsx
> +      onError: () => {},
fixed

2024-07-23 11:08 UTC, guardian-001 commented on src/app/(client)/(private)/(profile)/reset-password-client.tsx
> -      <ResetStepper initialStep={1} />
no utility

2024-07-23 11:11 UTC, guardian-001 commented on src/app/(client)/(private)/(projet)/publication-projet.tsx
> -import PublicationProjetStepper from '@/modules/client/pubication-projet/publication-projet-stepper';
typo sry 
![image](https://github.com/user-attachments/assets/eb413b91-072e-43b4-82e3-475310d79dcc)
fixed

2024-07-23 11:11 UTC, guardian-001 commented on src/modules/shared/stepper-percentage-bar.tsx
> +  const percentage = maxStep && (step / maxStep) * 100;
i dind't understand

2024-07-23 11:12 UTC, guardian-001 commented on src/modules/shared/stepper-percentage-bar.tsx
> +  const percentage = maxStep && (step / maxStep) * 100;
Do you mean a function to calculate the percentage?

2024-07-24 08:08 UTC, MohamedMegdich1 approved these changes

2024-07-24 08:08 UTC, merged