Oe/86bz12tn4/realization stepper v2
archimatchproject/mobile pull request #44
Opened 2024-07-26 05:28 UTC by guardian-001

I ran this PR just to ensure that the number of files changed is not high. The work is not complete
folders and files structure will be updated in the last pr

2024-07-27 08:20 UTC, Ghazi-Chaftar requested changes
left comments

2024-07-27 08:20 UTC, Ghazi-Chaftar commented on src/api/architect/project/use-needs.tsx
> +  fetcher: () => {
extract into a service file

2024-07-27 08:20 UTC, Ghazi-Chaftar commented on src/api/architect/user/use-data-architect.tsx
> +// api/styles.ts
remove gpt comment

2024-07-27 08:20 UTC, Ghazi-Chaftar commented on src/app/(supplier)/(public)/login.tsx
> +  // const signIn = useAuth.use.signIn();
comment

2024-07-27 08:20 UTC, Ghazi-Chaftar commented on src/app/(supplier)/(public)/login.tsx
> +    // signIn({
comment

2024-07-27 08:20 UTC, Ghazi-Chaftar commented on src/modules/architect/realization/shared/components/image-picker.tsx
> +        onPressHandler={() => {}} //uploadImages
empty function ! remove it please

2024-07-27 08:20 UTC, Ghazi-Chaftar commented on src/modules/architect/realization/shared/components/image-picker.tsx
> +        onPressHandler={() => {}} //uploadImages
remove comment

2024-07-27 08:20 UTC, Ghazi-Chaftar commented on src/modules/architect/realization/steps/adopted-style.tsx
> +    setFormData((prev: any) => ({
can't we type this

2024-07-27 08:20 UTC, Ghazi-Chaftar commented on src/modules/architect/realization/steps/approved-services.tsx
> +    // errors
remove comment

2024-07-27 08:20 UTC, Ghazi-Chaftar commented on src/modules/architect/realization/steps/approved-services.tsx
> +  console.log('error: ', error);
remove console log

2024-07-27 08:20 UTC, Ghazi-Chaftar commented on src/modules/architect/realization/steps/approved-services.tsx
> +  // const error = errors.needs?.message as TxKeyPath | undefined;
comment

2024-07-27 08:20 UTC, Ghazi-Chaftar commented on src/modules/architect/realization/steps/approved-services.tsx
> +          {isPending ? (
dont use ? : use && instead for more readablity of the code

2024-07-27 08:20 UTC, Ghazi-Chaftar commented on src/modules/architect/realization/steps/project-details.tsx
> +  useEffect(() => {
remove this

2024-07-27 08:20 UTC, Ghazi-Chaftar commented on src/modules/architect/realization/steps/project-details.tsx
> +  // const projectNameError = errors.description?.message as TxKeyPath | undefined;
comment

2024-07-27 08:20 UTC, Ghazi-Chaftar commented on src/modules/login/login-form.tsx
> +        console.log(response);
console log

2024-07-27 08:20 UTC, Ghazi-Chaftar commented on src/shared/components/image-uploader.tsx
> +// import React from 'react';
remove this file

2024-07-28 06:26 UTC, guardian-001 commented on src/modules/architect/realization/steps/approved-services.tsx
> +          {isPending ? (
i need the else property here, it's better to use ?

2024-07-28 06:26 UTC, guardian-001 commented on src/modules/architect/realization/steps/approved-services.tsx
> +  // const error = errors.needs?.message as TxKeyPath | undefined;
removed

2024-07-28 06:26 UTC, guardian-001 commented on src/modules/architect/realization/steps/approved-services.tsx
> +  console.log('error: ', error);
removed

2024-07-28 06:26 UTC, guardian-001 commented on src/modules/architect/realization/steps/approved-services.tsx
> +    // errors
removed

2024-07-28 06:26 UTC, guardian-001 commented on src/modules/architect/realization/steps/adopted-style.tsx
> +    setFormData((prev: any) => ({
already in last pr

2024-07-28 06:27 UTC, guardian-001 commented on src/modules/architect/realization/shared/components/image-picker.tsx
> +        onPressHandler={() => {}} //uploadImages
removed

2024-07-28 06:28 UTC, guardian-001 commented on src/modules/architect/realization/shared/components/image-picker.tsx
> +        onPressHandler={() => {}} //uploadImages
i already added a comment to explain that this function will be in the future a function to upload images, 
already changed in last pr

2024-07-28 06:28 UTC, guardian-001 commented on src/app/(supplier)/(public)/login.tsx
> +    // signIn({
removed

2024-07-28 06:28 UTC, guardian-001 commented on src/app/(supplier)/(public)/login.tsx
> +  // const signIn = useAuth.use.signIn();
removed

2024-07-28 06:28 UTC, guardian-001 commented on src/api/architect/user/use-data-architect.tsx
> +// api/styles.ts
removed

2024-07-28 06:28 UTC, guardian-001 commented on src/modules/architect/realization/steps/project-details.tsx
> +  useEffect(() => {
removed

2024-07-28 06:28 UTC, guardian-001 commented on src/modules/architect/realization/steps/project-details.tsx
> +  // const projectNameError = errors.description?.message as TxKeyPath | undefined;
removed

2024-07-28 06:28 UTC, guardian-001 commented on src/modules/login/login-form.tsx
> +        console.log(response);
removed

2024-07-28 06:29 UTC, guardian-001 commented on src/shared/components/image-uploader.tsx
> +// import React from 'react';
removed

2024-07-28 08:52 UTC, merged