fix(landing-page):bugfix
archimatchproject/mobile pull request #54
Opened 2024-07-31 09:41 UTC by Ahmedjaziri3

## What does this do?

This PR addresses a UI rendering issue in iOS for a React Native application. It updates the `GradientBackground` component to ensure that styles are correctly applied, which solves the problem where the gradient background was not displaying as expected. The changes include modifying the usage of the `LinearGradient` component to properly handle the `className` prop by applying styles directly.

## Note:

This Update will be followed with multiple bugs fix updates before review 

## Why did you do this?

The changes were made to fix a rendering issue on iOS devices where the gradient background was not appearing correctly. By ensuring that the styles are applied properly, the UI now displays as intended, providing a consistent user experience across different platforms.

## Who/what does this impact?

These changes impact the `GradientBackground` component, which may be used in multiple places within the application. It's important for other developers who are working on UI components that use this gradient background to be aware of the changes. The changes should not have any adverse side effects but will enhance the visual consistency on iOS devices.

## How did you test this?

The changes were tested by running the application on both iOS and Android devices to ensure the gradient background renders correctly on all platforms. Visual inspections were performed to confirm that the styles are applied as expected and that the UI elements display properly without any layout issues.

## images reflect the first change:

![image](https://github.com/user-attachments/assets/f1763e02-6fc0-4d01-863b-08ecbfbae11e)

![image](https://github.com/user-attachments/assets/9bd75f6d-9d6e-462f-94eb-726a6513560b)

![image](https://github.com/user-attachments/assets/6facaf3b-4778-47c8-8df6-886b21c94126)

2024-07-31 11:13 UTC, Ahmedjaziri3 commented
## What does this do?
Updates the landing page to set a default background color for the button. This ensures consistent button appearance and avoids color conflicts with different users' dynamic themes or system settings mainly it happens in the ios.

## images reflect the first change:

## before:

<img width="240" alt="Capture d’écran 2024-07-31 à 12 09 27 PM" src="https://github.com/user-attachments/assets/c691d2ab-2813-4a8f-92ac-8744a457c044">

## after:

<img width="606" alt="Capture d’écran 2024-07-31 à 12 05 42 PM" src="https://github.com/user-attachments/assets/49a2562f-df09-4b24-b79e-d4c9523d9329">

2024-08-01 15:24 UTC, Ahmedjaziri3 commented
## before:

<img width="1440" alt="Capture d’écran 2024-07-29 à 12 50 37 PM" src="https://github.com/user-attachments/assets/13c04dbc-a394-4609-9921-6209f7fb4528">

<img width="1440" alt="Capture d’écran 2024-07-29 à 12 51 14 PM" src="https://github.com/user-attachments/assets/70e8a058-bf87-4604-af4b-5381e8e468b1">

<img width="1440" alt="Capture d’écran 2024-07-29 à 12 51 24 PM" src="https://github.com/user-attachments/assets/1bd5d6dd-b450-481f-838e-56a7db68a9a7">

<img width="1440" alt="Capture d’écran 2024-07-29 à 12 50 27 PM" src="https://github.com/user-attachments/assets/4575172c-2067-4d0f-8ca9-938c58b5bc99">

<img width="379" alt="Capture d’écran 2024-07-29 à 12 36 03 PM 2" src="https://github.com/user-attachments/assets/8ec3c926-9509-4149-adb2-e3183270947d">

<img width="1440" alt="Capture d’écran 2024-07-29 à 12 52 18 PM" src="https://github.com/user-attachments/assets/e73449ca-9618-47ea-87a9-3e99f80ae8ff">

<img width="1440" alt="Capture d’écran 2024-07-29 à 12 51 42 PM" src="https://github.com/user-attachments/assets/0b1e3423-ad27-40e2-8cd9-04e8d3ce8dd4">

<img width="1440" alt="Capture d’écran 2024-07-29 à 12 51 48 PM" src="https://github.com/user-attachments/assets/d514666c-5d2d-453a-85aa-20e6e007d452">


<img width="1440" alt="Capture d’écran 2024-07-29 à 2 05 41 PM" src="https://github.com/user-attachments/assets/7588e8c9-eebb-4825-8476-13121931dc0e">


## After:

<img width="307" alt="Capture d’écran 2024-07-31 à 10 26 44 PM" src="https://github.com/user-attachments/assets/5c6f365e-64af-436e-a815-4af288bbc736">

<img width="305" alt="Capture d’écran 2024-07-31 à 10 28 23 PM" src="https://github.com/user-attachments/assets/2d60f5e6-0f20-4c1e-a58e-ea070b94e3d8">

<img width="306" alt="Capture d’écran 2024-07-31 à 10 29 43 PM" src="https://github.com/user-attachments/assets/2886d481-0ea6-4f42-b014-f2e586e4d6b6">


<img width="328" alt="Capture d’écran 2024-08-01 à 11 55 06 AM" src="https://github.com/user-attachments/assets/37c46cc6-4312-4a02-b887-2cf7a405d7ab">

<img width="334" alt="Capture d’écran 2024-08-01 à 11 56 54 AM" src="https://github.com/user-attachments/assets/69938c34-4499-494d-b8f8-3658768ff8e7">

## Before:

<img width="335" alt="Capture d’écran 2024-07-31 à 10 31 28 PM" src="https://github.com/user-attachments/assets/5bd93a1a-6938-41e1-ac07-901799e88701">

## After:

<img width="331" alt="Capture d’écran 2024-08-01 à 11 31 53 AM" src="https://github.com/user-attachments/assets/d98947fe-ba28-4285-b4b9-74014d642ebe">

2024-08-02 09:15 UTC, khalil7898 requested changes
emove the classeName from props typing for impacted component and add nice commne texplaining the why with PR link

2024-08-02 09:15 UTC, khalil7898 commented on src/shared/components/gradient-background.tsx
> +type GradientBackgroundProps = {
emove the classeName from props typing for impacted component   and add nice commne texplaining the why with PR link

2024-08-02 13:00 UTC, MohamedMegdich1 commented on src/shared/components/header-title.tsx
> +          style={{
Why not use a StyleSheet instead?

2024-08-02 14:38 UTC, Ahmedjaziri3 commented on src/shared/components/header-title.tsx
> +            style={{
In some cases, using StyleSheet.create for specific styles like marginTop: 40 can make the code more consistent and readable, especially if such a style doesnt showed up in ios when i use mt with tailwind

2024-08-02 14:55 UTC, merged