feat(catalogue): add products
archimatchproject/mobile pull request #96
Opened 2024-09-01 06:35 UTC by guardian-001

add products to specifique collection

2024-09-02 08:05 UTC, MohamedMegdich1 requested changes

2024-09-02 08:05 UTC, MohamedMegdich1 commented on src/modules/supplier/shared/schema/collection-schema.tsx
> +  name: z.string().min(1, 'Name is required'),
Please remember to use reusable schema and ensure accurate translation of messages.

2024-09-02 08:05 UTC, MohamedMegdich1 commented on src/shared/components/tag.tsx
> +  onChange,
why handling onChange from outside

2024-09-02 08:05 UTC, MohamedMegdich1 commented on src/modules/supplier/catalogue/schema/collection-schema.tsx
> +export const productSchema = z.object({
Please remember to use reusable schema and ensure accurate translation of messages.

2024-09-02 08:05 UTC, MohamedMegdich1 commented on src/modules/supplier/catalogue/hooks/use-profile-catalogue.tsx
> +    console.log(selectedCollectionId);
remove this

2024-09-02 08:05 UTC, MohamedMegdich1 commented on src/modules/supplier/catalogue/hooks/use-image-picker.tsx
> +  const pickImages = async () => {
I think you can configure the image picker to only select images.

2024-09-02 08:10 UTC, guardian-001 commented on src/shared/components/tag.tsx
> +  onChange,
Because using the tag can handle changes outside of it, for example, in this PR, the handling of products in a specific collection depends on the collection selection, which are represented by tags

2024-09-02 08:28 UTC, guardian-001 commented on src/modules/supplier/catalogue/hooks/use-image-picker.tsx
> +  const pickImages = async () => {
Already done, 
 
![image](https://github.com/user-attachments/assets/f21dcc20-868b-4839-bc0e-acaf82f3c391)

2024-09-03 12:11 UTC, guardian-001 commented on src/modules/supplier/catalogue/schema/collection-schema.tsx
> +export const productSchema = z.object({
fixed

2024-09-03 12:11 UTC, guardian-001 commented on src/modules/supplier/shared/schema/collection-schema.tsx
> +  name: z.string().min(1, 'Name is required'),
fixed

2024-09-04 07:02 UTC, merged