Oe/supplier/catalogue v5
archimatchproject/mobile pull request #97
Opened 2024-09-02 07:53 UTC by guardian-001

- Display products depending on appearance 
- Search implementation 
- Img slider in product component

2024-09-02 08:12 UTC, MohamedMegdich1 requested changes

2024-09-02 08:12 UTC, MohamedMegdich1 commented on src/modules/supplier/catalogue/components/images-list.tsx
> +              index === Math.floor(images.length / 3) &&
Extract the logic outside

2024-09-02 08:12 UTC, MohamedMegdich1 commented on src/modules/supplier/catalogue/components/products-big-grid.tsx
> +            id: -1,
extract it outside

2024-09-02 08:12 UTC, MohamedMegdich1 commented on src/modules/supplier/catalogue/components/products-little-grid.tsx
> +            id: -1,
define a reusable constant instead

2024-09-02 08:12 UTC, MohamedMegdich1 commented on src/modules/supplier/catalogue/hooks/use-image-picker.tsx
> +  const removeImage = (index: number, subIndex: number) => {
It is not recommended to work with index.

2024-09-02 08:12 UTC, MohamedMegdich1 commented on src/modules/supplier/catalogue/hooks/use-profile-catalogue.tsx
> +      CollectionData?.filter((cd) => cd.id === selectedCollectionId)[0]
hhhhh dvd Please change it

2024-09-02 08:12 UTC, MohamedMegdich1 commented on src/modules/supplier/catalogue/schema/collection-schema.tsx
> +  id: z.number().nonnegative(),
use reusable schema and translate the message

2024-09-02 08:12 UTC, MohamedMegdich1 commented on src/modules/supplier/profile/type/index.ts
> +  appearance: 'Petite' | 'Grande';
translation

2024-09-02 08:12 UTC, MohamedMegdich1 commented on src/modules/supplier/shared/schema/collection-schema.tsx
> +export const productSchema = z.object({
use reusable schema and translate the message

2024-09-02 08:12 UTC, MohamedMegdich1 commented on src/shared/components/controlled-input.tsx
> +      value={forcedValue ? forcedValue : (field.value as string) || ''}
Why are you adding the forcedValue prop

2024-09-02 08:32 UTC, guardian-001 commented on src/modules/supplier/catalogue/hooks/use-profile-catalogue.tsx
> +      CollectionData?.filter((cd) => cd.id === selectedCollectionId)[0]
😂😂😂 changed

2024-09-03 12:21 UTC, guardian-001 commented on src/modules/supplier/catalogue/components/images-list.tsx
> +              index === Math.floor(images.length / 3) &&
fixed in pr #96

2024-09-03 12:31 UTC, guardian-001 commented on src/modules/supplier/catalogue/components/products-big-grid.tsx
> +            id: -1,
extracted :
![image](https://github.com/user-attachments/assets/7ccec43a-0a90-469b-bc46-1d3f2963bf47)

![image](https://github.com/user-attachments/assets/a96b7418-1588-4714-a787-01d023e3e06d)

2024-09-03 12:32 UTC, guardian-001 commented on src/modules/supplier/catalogue/schema/collection-schema.tsx
> +  id: z.number().nonnegative(),
fixed in pr #96

2024-09-03 12:45 UTC, guardian-001 commented on src/modules/supplier/profile/type/index.ts
> +  appearance: 'Petite' | 'Grande';
In the backend, the value is saved like this; the value displayed in the UI is translated, with only the type being shown here (I followed the web part)

2024-09-03 12:56 UTC, guardian-001 commented on src/shared/components/controlled-input.tsx
> +      value={forcedValue ? forcedValue : (field.value as string) || ''}
Because this field is pre-filled with the title of the collection to which I will add a product, I added the forcedValue variable because I want the title to be shown in the field and for the field's value to contain the ID of the collection, not the title.
The current value of the field:
![image](https://github.com/user-attachments/assets/026d1519-b055-47fe-87b1-bf7ddcab4b71)

The value that I want to be shown:
![WhatsApp Image 2024-09-03 à 13 54 33_e9a72bca](https://github.com/user-attachments/assets/a221b38e-7809-47b6-a0b3-0ab83dc31548)

2024-09-03 12:58 UTC, guardian-001 commented on src/modules/supplier/catalogue/hooks/use-image-picker.tsx
> +  const removeImage = (index: number, subIndex: number) => {
The images don't have IDs. If there is another solution, please let me know

2024-09-03 12:58 UTC, guardian-001 commented on src/modules/supplier/catalogue/components/products-little-grid.tsx
> +            id: -1,
done:
![image](https://github.com/user-attachments/assets/74bc7c06-4003-4052-8532-68d73a20979e)
![image](https://github.com/user-attachments/assets/e6ac7f5c-4120-4e73-9410-542b2596d73e)

2024-09-04 07:02 UTC, merged